---
title: "Final Project"
author: "Mike Secosky"
date: "12/9/2019"
output: html_document
---



```{r}
library(DataComputing)
library(tidyverse)
```

Research Question: Has the amount of people over the age of 50 who at least occasionally use the internet increased since 2009?





```{r}
InternetUsage2019 <- read_csv("C:\\Users\\secos\\OneDrive\\Desktop\\College\\Stat 184\\January 8-February 7, 2019 - Core Trends Survey - CSV.csv")
```

```{r}
InternetUsage2009 <- read.csv("C:\\Users\\secos\\OneDrive\\Desktop\\College\\June 18-21, 2009 - Video Uploading - CSV.csv")
```

```{r}
glimpse(InternetUsage2009)
```


```{r}
glimpse(InternetUsage2019)
```

```{r}
Elderly2019 <-
InternetUsage2019 %>%
  select(age, sex, eminuse) %>%
  group_by(sex) %>%
  filter(grepl("1", eminuse, ignore.case = TRUE)) %>%
  filter(age >= 50) %>%
  summarise(use2019 = n())
```

```{r}
Elderly2009 <-
InternetUsage2009 %>%
  select(age, sex, neta) %>%
  group_by(sex) %>%
  filter(age >= 50) %>%
  filter(neta == 1) %>%
  summarise(use2009 = n())
```

```{r}
InternetGrowth <-
full_join(Elderly2009, Elderly2019)
```


```{r}
InternetGrowthGraph <-
InternetGrowth %>%
  gather(key = when, value = occuse, use2009, use2019)
```


```{r}
InternetGrowthGraph %>%
  ggplot(aes(x=when, y=occuse, fill = sex)) +
  geom_bar(stat = 'identity', position = 'stack', width = .9) +
  facet_wrap(~sex, ncol = 3)
```

```{r}
InternetUsage2009graph <-
InternetUsage2009 %>%
  select(age, sex, neta) %>%
  group_by(sex) %>%
  filter(age >= 50) %>%
  filter(neta < 3) %>%
  filter(age < 99)
```



```{r}
InternetUsage2009graph %>%
  ggplot(aes(x = age)) +
  geom_density() +
  geom_histogram(binwidth = 1.8, alpha = .5) +
  labs(title = "Histogram of at least Occasional Usage by Age")
```

